"""Deterministic chunked gated delta rule (GDN) training kernels for Blackwell (SM100a / SM103a).

Generated by the Cake compiler from the flash-linear-attention v0.5.2 ``chunk_gated_delta_rule``
dataflow (in-kernel q/k L2 normalisation, fp32 log-decay gate, chunk 64, K = V = 128): the
forward and the backward run as register-MMA kernels with fixed launch geometry, fixed-order
reductions and no atomics, so repeated forward and backward passes on identical inputs are
bit-identical. :func:`chunk_gated_delta_rule` has FLA's signature (``cu_seqlens`` packing,
``initial_state`` / ``output_final_state``, ``cp_context`` state passing) and is what
``--linear-attention-backend deterministic`` selects for the Qwen3.5 / Qwen3-Next GDN layers.
"""

from ._jit import SUPPORTED_CAPABILITIES, device_arch
from .ops import chunk_gated_delta_rule, deterministic_applies

__all__ = ["SUPPORTED_CAPABILITIES", "chunk_gated_delta_rule", "deterministic_applies", "device_arch"]
