"""
Copyright (c) 2026, NVIDIA CORPORATION. All rights reserved.
Licensed under the Apache License, Version 2.0.
https://www.apache.org/licenses/LICENSE-2.0

Native loading for the generated deterministic chunked GDN training kernels (SM100a / SM103a).

The registry is filled mechanically from the Cake compiler's resolved builds of
``loom.examples.weave.gdn_chunk_training``: one device/launcher source pair per kernel and
architecture under ``csrc/<arch>/``. Kernels that share a source (``fwd_h`` / ``fwd_h_v64``,
``dhu`` / ``dhu_v64``) share a module. Each kernel builds on first use as a torch CUDA
extension (``nvcc`` + ``ninja``; cached under ``TORCH_EXTENSIONS_DIR``).
"""

import os
from functools import cache
from pathlib import Path

import torch

_CSRC = Path(__file__).resolve().parent / "csrc"
_ARCH_FLAGS = {
    "sm_100a": "-gencode=arch=compute_100a,code=sm_100a",
    "sm_103a": "-gencode=arch=compute_103a,code=sm_103a",
}
SUPPORTED_CAPABILITIES = {(10, 0): "sm_100a", (10, 3): "sm_103a"}
# torch's extension build disables the half / bf16 conversion operators; the generated device code uses them.
_CONVERSION_FLAGS = (
    "-U__CUDA_NO_HALF_OPERATORS__",
    "-U__CUDA_NO_HALF_CONVERSIONS__",
    "-U__CUDA_NO_HALF2_OPERATORS__",
    "-U__CUDA_NO_BFLOAT16_CONVERSIONS__",
)

# MODULES[stage][arch] -> generated module record (mechanically filled).
MODULES = {
    "meta": {
        "sm_100a": {
            "name": "cake_gdn_chunk_train_8e5debffef07e906f8cb",
            "arch": "sm_100a",
            "cache_name": "cake_gdn_chunk_train_8e5debffef07e906f8cb_sm_100a",
            "kernel_symbol": "kernel_cake_gdn_chunk_train_8e5debffef07e906f8cb",
            "arg_plan": (
                ("buffer", "cu_seqlens"),
                ("buffer", "chunk_start"),
                ("buffer", "chunk_len"),
                ("buffer", "seq_chunk_start"),
                ("parameter", "num_seqs"),
                ("parameter", "num_chunks_max"),
                ("parameter", "total_tokens"),
                ("grid", "grid_x"),
                ("grid", "grid_y"),
                ("grid", "grid_z"),
            ),
            "sources": (
                "sm_100a/cake_gdn_chunk_train_8e5debffef07e906f8cb_kernel.cu",
                "sm_100a/cake_gdn_chunk_train_8e5debffef07e906f8cb_binding.cu",
            ),
            "block": (128, 1, 1),
            "dynamic_smem_bytes": 0,
            "tma_workspace_bytes": 0,
            "ffi_entry": "run",
            "compile_flags": (),
        },
        "sm_103a": {
            "name": "cake_gdn_chunk_train_6e5496c196a1285ec39d",
            "arch": "sm_103a",
            "cache_name": "cake_gdn_chunk_train_6e5496c196a1285ec39d_sm_103a",
            "kernel_symbol": "kernel_cake_gdn_chunk_train_6e5496c196a1285ec39d",
            "arg_plan": (
                ("buffer", "cu_seqlens"),
                ("buffer", "chunk_start"),
                ("buffer", "chunk_len"),
                ("buffer", "seq_chunk_start"),
                ("parameter", "num_seqs"),
                ("parameter", "num_chunks_max"),
                ("parameter", "total_tokens"),
                ("grid", "grid_x"),
                ("grid", "grid_y"),
                ("grid", "grid_z"),
            ),
            "sources": (
                "sm_103a/cake_gdn_chunk_train_6e5496c196a1285ec39d_kernel.cu",
                "sm_103a/cake_gdn_chunk_train_6e5496c196a1285ec39d_binding.cu",
            ),
            "block": (128, 1, 1),
            "dynamic_smem_bytes": 0,
            "tma_workspace_bytes": 0,
            "ffi_entry": "run",
            "compile_flags": (),
        },
    },
    "prep": {
        "sm_100a": {
            "name": "cake_gdn_chunk_train_79675869a77088c714d1",
            "arch": "sm_100a",
            "cache_name": "cake_gdn_chunk_train_79675869a77088c714d1_sm_100a",
            "kernel_symbol": "kernel_cake_gdn_chunk_train_79675869a77088c714d1",
            "arg_plan": (
                ("buffer", "q"),
                ("buffer", "k"),
                ("buffer", "g"),
                ("buffer", "beta"),
                ("buffer", "beta32_out"),
                ("buffer", "qn"),
                ("buffer", "kn"),
                ("buffer", "rstd_q"),
                ("buffer", "rstd_k"),
                ("buffer", "g_cs"),
                ("buffer", "chunk_start"),
                ("buffer", "chunk_len"),
                ("parameter", "num_heads"),
                ("parameter", "num_v_heads"),
                ("parameter", "normalize_qk"),
                ("grid", "grid_x"),
                ("grid", "grid_y"),
                ("grid", "grid_z"),
            ),
            "sources": (
                "sm_100a/cake_gdn_chunk_train_79675869a77088c714d1_kernel.cu",
                "sm_100a/cake_gdn_chunk_train_79675869a77088c714d1_binding.cu",
            ),
            "block": (128, 1, 1),
            "dynamic_smem_bytes": 0,
            "tma_workspace_bytes": 0,
            "ffi_entry": "run",
            "compile_flags": (),
        },
        "sm_103a": {
            "name": "cake_gdn_chunk_train_9476c06edd2f1dc5bd5a",
            "arch": "sm_103a",
            "cache_name": "cake_gdn_chunk_train_9476c06edd2f1dc5bd5a_sm_103a",
            "kernel_symbol": "kernel_cake_gdn_chunk_train_9476c06edd2f1dc5bd5a",
            "arg_plan": (
                ("buffer", "q"),
                ("buffer", "k"),
                ("buffer", "g"),
                ("buffer", "beta"),
                ("buffer", "beta32_out"),
                ("buffer", "qn"),
                ("buffer", "kn"),
                ("buffer", "rstd_q"),
                ("buffer", "rstd_k"),
                ("buffer", "g_cs"),
                ("buffer", "chunk_start"),
                ("buffer", "chunk_len"),
                ("parameter", "num_heads"),
                ("parameter", "num_v_heads"),
                ("parameter", "normalize_qk"),
                ("grid", "grid_x"),
                ("grid", "grid_y"),
                ("grid", "grid_z"),
            ),
            "sources": (
                "sm_103a/cake_gdn_chunk_train_9476c06edd2f1dc5bd5a_kernel.cu",
                "sm_103a/cake_gdn_chunk_train_9476c06edd2f1dc5bd5a_binding.cu",
            ),
            "block": (128, 1, 1),
            "dynamic_smem_bytes": 0,
            "tma_workspace_bytes": 0,
            "ffi_entry": "run",
            "compile_flags": (),
        },
    },
    "prep_bf16beta": {
        "sm_100a": {
            "name": "cake_gdn_chunk_train_99ba0855e2578a159dc1",
            "arch": "sm_100a",
            "cache_name": "cake_gdn_chunk_train_99ba0855e2578a159dc1_sm_100a",
            "kernel_symbol": "kernel_cake_gdn_chunk_train_99ba0855e2578a159dc1",
            "arg_plan": (
                ("buffer", "q"),
                ("buffer", "k"),
                ("buffer", "g"),
                ("buffer", "beta"),
                ("buffer", "beta32_out"),
                ("buffer", "qn"),
                ("buffer", "kn"),
                ("buffer", "rstd_q"),
                ("buffer", "rstd_k"),
                ("buffer", "g_cs"),
                ("buffer", "chunk_start"),
                ("buffer", "chunk_len"),
                ("parameter", "num_heads"),
                ("parameter", "num_v_heads"),
                ("parameter", "normalize_qk"),
                ("grid", "grid_x"),
                ("grid", "grid_y"),
                ("grid", "grid_z"),
            ),
            "sources": (
                "sm_100a/cake_gdn_chunk_train_99ba0855e2578a159dc1_kernel.cu",
                "sm_100a/cake_gdn_chunk_train_99ba0855e2578a159dc1_binding.cu",
            ),
            "block": (128, 1, 1),
            "dynamic_smem_bytes": 0,
            "tma_workspace_bytes": 0,
            "ffi_entry": "run",
            "compile_flags": (),
        },
        "sm_103a": {
            "name": "cake_gdn_chunk_train_308ac3dccab2d92946ab",
            "arch": "sm_103a",
            "cache_name": "cake_gdn_chunk_train_308ac3dccab2d92946ab_sm_103a",
            "kernel_symbol": "kernel_cake_gdn_chunk_train_308ac3dccab2d92946ab",
            "arg_plan": (
                ("buffer", "q"),
                ("buffer", "k"),
                ("buffer", "g"),
                ("buffer", "beta"),
                ("buffer", "beta32_out"),
                ("buffer", "qn"),
                ("buffer", "kn"),
                ("buffer", "rstd_q"),
                ("buffer", "rstd_k"),
                ("buffer", "g_cs"),
                ("buffer", "chunk_start"),
                ("buffer", "chunk_len"),
                ("parameter", "num_heads"),
                ("parameter", "num_v_heads"),
                ("parameter", "normalize_qk"),
                ("grid", "grid_x"),
                ("grid", "grid_y"),
                ("grid", "grid_z"),
            ),
            "sources": (
                "sm_103a/cake_gdn_chunk_train_308ac3dccab2d92946ab_kernel.cu",
                "sm_103a/cake_gdn_chunk_train_308ac3dccab2d92946ab_binding.cu",
            ),
            "block": (128, 1, 1),
            "dynamic_smem_bytes": 0,
            "tma_workspace_bytes": 0,
            "ffi_entry": "run",
            "compile_flags": (),
        },
    },
    "wy": {
        "sm_100a": {
            "name": "cake_gdn_chunk_train_7af3251a242e15dbaeb4",
            "arch": "sm_100a",
            "cache_name": "cake_gdn_chunk_train_7af3251a242e15dbaeb4_sm_100a",
            "kernel_symbol": "kernel_cake_gdn_chunk_train_7af3251a242e15dbaeb4",
            "arg_plan": (
                ("buffer", "kn"),
                ("buffer", "v"),
                ("buffer", "g_cs"),
                ("buffer", "beta"),
                ("buffer", "A_out"),
                ("buffer", "w_out"),
                ("buffer", "u_out"),
                ("buffer", "chunk_start"),
                ("buffer", "chunk_len"),
                ("parameter", "num_heads"),
                ("parameter", "num_v_heads"),
                ("parameter", "recompute"),
                ("grid", "grid_x"),
                ("grid", "grid_y"),
                ("grid", "grid_z"),
            ),
            "sources": (
                "sm_100a/cake_gdn_chunk_train_7af3251a242e15dbaeb4_kernel.cu",
                "sm_100a/cake_gdn_chunk_train_7af3251a242e15dbaeb4_binding.cu",
            ),
            "block": (128, 1, 1),
            "dynamic_smem_bytes": 93696,
            "tma_workspace_bytes": 0,
            "ffi_entry": "run",
            "compile_flags": (),
        },
        "sm_103a": {
            "name": "cake_gdn_chunk_train_4505b5fc9224595f3c75",
            "arch": "sm_103a",
            "cache_name": "cake_gdn_chunk_train_4505b5fc9224595f3c75_sm_103a",
            "kernel_symbol": "kernel_cake_gdn_chunk_train_4505b5fc9224595f3c75",
            "arg_plan": (
                ("buffer", "kn"),
                ("buffer", "v"),
                ("buffer", "g_cs"),
                ("buffer", "beta"),
                ("buffer", "A_out"),
                ("buffer", "w_out"),
                ("buffer", "u_out"),
                ("buffer", "chunk_start"),
                ("buffer", "chunk_len"),
                ("parameter", "num_heads"),
                ("parameter", "num_v_heads"),
                ("parameter", "recompute"),
                ("grid", "grid_x"),
                ("grid", "grid_y"),
                ("grid", "grid_z"),
            ),
            "sources": (
                "sm_103a/cake_gdn_chunk_train_4505b5fc9224595f3c75_kernel.cu",
                "sm_103a/cake_gdn_chunk_train_4505b5fc9224595f3c75_binding.cu",
            ),
            "block": (128, 1, 1),
            "dynamic_smem_bytes": 93696,
            "tma_workspace_bytes": 0,
            "ffi_entry": "run",
            "compile_flags": (),
        },
    },
    "fwd_h": {
        "sm_100a": {
            "name": "cake_gdn_chunk_train_665c0a5bab5b45eed969",
            "arch": "sm_100a",
            "cache_name": "cake_gdn_chunk_train_665c0a5bab5b45eed969_sm_100a",
            "kernel_symbol": "kernel_cake_gdn_chunk_train_665c0a5bab5b45eed969",
            "arg_plan": (
                ("buffer", "kn"),
                ("buffer", "w"),
                ("buffer", "u"),
                ("buffer", "g_cs"),
                ("buffer", "h0"),
                ("buffer", "h_out"),
                ("buffer", "v_new"),
                ("buffer", "final_state"),
                ("buffer", "chunk_start"),
                ("buffer", "chunk_len"),
                ("buffer", "seq_chunk_start"),
                ("parameter", "num_heads"),
                ("parameter", "num_v_heads"),
                ("parameter", "use_initial_state"),
                ("parameter", "store_final_state"),
                ("grid", "grid_x"),
                ("grid", "grid_y"),
                ("grid", "grid_z"),
            ),
            "sources": (
                "sm_100a/cake_gdn_chunk_train_665c0a5bab5b45eed969_kernel.cu",
                "sm_100a/cake_gdn_chunk_train_665c0a5bab5b45eed969_binding.cu",
            ),
            "block": (128, 1, 1),
            "dynamic_smem_bytes": 106752,
            "tma_workspace_bytes": 0,
            "ffi_entry": "run",
            "compile_flags": (),
        },
        "sm_103a": {
            "name": "cake_gdn_chunk_train_1078bc5fcca39c5dd120",
            "arch": "sm_103a",
            "cache_name": "cake_gdn_chunk_train_1078bc5fcca39c5dd120_sm_103a",
            "kernel_symbol": "kernel_cake_gdn_chunk_train_1078bc5fcca39c5dd120",
            "arg_plan": (
                ("buffer", "kn"),
                ("buffer", "w"),
                ("buffer", "u"),
                ("buffer", "g_cs"),
                ("buffer", "h0"),
                ("buffer", "h_out"),
                ("buffer", "v_new"),
                ("buffer", "final_state"),
                ("buffer", "chunk_start"),
                ("buffer", "chunk_len"),
                ("buffer", "seq_chunk_start"),
                ("parameter", "num_heads"),
                ("parameter", "num_v_heads"),
                ("parameter", "use_initial_state"),
                ("parameter", "store_final_state"),
                ("grid", "grid_x"),
                ("grid", "grid_y"),
                ("grid", "grid_z"),
            ),
            "sources": (
                "sm_103a/cake_gdn_chunk_train_1078bc5fcca39c5dd120_kernel.cu",
                "sm_103a/cake_gdn_chunk_train_1078bc5fcca39c5dd120_binding.cu",
            ),
            "block": (128, 1, 1),
            "dynamic_smem_bytes": 106752,
            "tma_workspace_bytes": 0,
            "ffi_entry": "run",
            "compile_flags": (),
        },
    },
    "fwd_o": {
        "sm_100a": {
            "name": "cake_gdn_chunk_train_d308d9806b1a9747ba62",
            "arch": "sm_100a",
            "cache_name": "cake_gdn_chunk_train_d308d9806b1a9747ba62_sm_100a",
            "kernel_symbol": "kernel_cake_gdn_chunk_train_d308d9806b1a9747ba62",
            "arg_plan": (
                ("buffer", "qn"),
                ("buffer", "kn"),
                ("buffer", "v_new"),
                ("buffer", "h"),
                ("buffer", "g_cs"),
                ("buffer", "o_out"),
                ("buffer", "chunk_start"),
                ("buffer", "chunk_len"),
                ("parameter", "num_heads"),
                ("parameter", "num_v_heads"),
                ("parameter", "scale"),
                ("grid", "grid_x"),
                ("grid", "grid_y"),
                ("grid", "grid_z"),
            ),
            "sources": (
                "sm_100a/cake_gdn_chunk_train_d308d9806b1a9747ba62_kernel.cu",
                "sm_100a/cake_gdn_chunk_train_d308d9806b1a9747ba62_binding.cu",
            ),
            "block": (128, 1, 1),
            "dynamic_smem_bytes": 90368,
            "tma_workspace_bytes": 0,
            "ffi_entry": "run",
            "compile_flags": (),
        },
        "sm_103a": {
            "name": "cake_gdn_chunk_train_5201362b8ee94531c31f",
            "arch": "sm_103a",
            "cache_name": "cake_gdn_chunk_train_5201362b8ee94531c31f_sm_103a",
            "kernel_symbol": "kernel_cake_gdn_chunk_train_5201362b8ee94531c31f",
            "arg_plan": (
                ("buffer", "qn"),
                ("buffer", "kn"),
                ("buffer", "v_new"),
                ("buffer", "h"),
                ("buffer", "g_cs"),
                ("buffer", "o_out"),
                ("buffer", "chunk_start"),
                ("buffer", "chunk_len"),
                ("parameter", "num_heads"),
                ("parameter", "num_v_heads"),
                ("parameter", "scale"),
                ("grid", "grid_x"),
                ("grid", "grid_y"),
                ("grid", "grid_z"),
            ),
            "sources": (
                "sm_103a/cake_gdn_chunk_train_5201362b8ee94531c31f_kernel.cu",
                "sm_103a/cake_gdn_chunk_train_5201362b8ee94531c31f_binding.cu",
            ),
            "block": (128, 1, 1),
            "dynamic_smem_bytes": 90368,
            "tma_workspace_bytes": 0,
            "ffi_entry": "run",
            "compile_flags": (),
        },
    },
    "fwd_h_v64": {
        "sm_100a": {
            "name": "cake_gdn_chunk_train_665c0a5bab5b45eed969",
            "arch": "sm_100a",
            "cache_name": "cake_gdn_chunk_train_665c0a5bab5b45eed969_sm_100a",
            "kernel_symbol": "kernel_cake_gdn_chunk_train_665c0a5bab5b45eed969",
            "arg_plan": (
                ("buffer", "kn"),
                ("buffer", "w"),
                ("buffer", "u"),
                ("buffer", "g_cs"),
                ("buffer", "h0"),
                ("buffer", "h_out"),
                ("buffer", "v_new"),
                ("buffer", "final_state"),
                ("buffer", "chunk_start"),
                ("buffer", "chunk_len"),
                ("buffer", "seq_chunk_start"),
                ("parameter", "num_heads"),
                ("parameter", "num_v_heads"),
                ("parameter", "use_initial_state"),
                ("parameter", "store_final_state"),
                ("grid", "grid_x"),
                ("grid", "grid_y"),
                ("grid", "grid_z"),
            ),
            "sources": (
                "sm_100a/cake_gdn_chunk_train_665c0a5bab5b45eed969_kernel.cu",
                "sm_100a/cake_gdn_chunk_train_665c0a5bab5b45eed969_binding.cu",
            ),
            "block": (128, 1, 1),
            "dynamic_smem_bytes": 106752,
            "tma_workspace_bytes": 0,
            "ffi_entry": "run",
            "compile_flags": (),
        },
        "sm_103a": {
            "name": "cake_gdn_chunk_train_1078bc5fcca39c5dd120",
            "arch": "sm_103a",
            "cache_name": "cake_gdn_chunk_train_1078bc5fcca39c5dd120_sm_103a",
            "kernel_symbol": "kernel_cake_gdn_chunk_train_1078bc5fcca39c5dd120",
            "arg_plan": (
                ("buffer", "kn"),
                ("buffer", "w"),
                ("buffer", "u"),
                ("buffer", "g_cs"),
                ("buffer", "h0"),
                ("buffer", "h_out"),
                ("buffer", "v_new"),
                ("buffer", "final_state"),
                ("buffer", "chunk_start"),
                ("buffer", "chunk_len"),
                ("buffer", "seq_chunk_start"),
                ("parameter", "num_heads"),
                ("parameter", "num_v_heads"),
                ("parameter", "use_initial_state"),
                ("parameter", "store_final_state"),
                ("grid", "grid_x"),
                ("grid", "grid_y"),
                ("grid", "grid_z"),
            ),
            "sources": (
                "sm_103a/cake_gdn_chunk_train_1078bc5fcca39c5dd120_kernel.cu",
                "sm_103a/cake_gdn_chunk_train_1078bc5fcca39c5dd120_binding.cu",
            ),
            "block": (128, 1, 1),
            "dynamic_smem_bytes": 106752,
            "tma_workspace_bytes": 0,
            "ffi_entry": "run",
            "compile_flags": (),
        },
    },
    "fwd_h_v32": {
        "sm_100a": {
            "name": "cake_gdn_chunk_train_52c9eb9acaf6543b11c2",
            "arch": "sm_100a",
            "cache_name": "cake_gdn_chunk_train_52c9eb9acaf6543b11c2_sm_100a",
            "kernel_symbol": "kernel_cake_gdn_chunk_train_52c9eb9acaf6543b11c2",
            "arg_plan": (
                ("buffer", "kn"),
                ("buffer", "w"),
                ("buffer", "u"),
                ("buffer", "g_cs"),
                ("buffer", "h0"),
                ("buffer", "h_out"),
                ("buffer", "v_new"),
                ("buffer", "final_state"),
                ("buffer", "chunk_start"),
                ("buffer", "chunk_len"),
                ("buffer", "seq_chunk_start"),
                ("parameter", "num_heads"),
                ("parameter", "num_v_heads"),
                ("parameter", "use_initial_state"),
                ("parameter", "store_final_state"),
                ("grid", "grid_x"),
                ("grid", "grid_y"),
                ("grid", "grid_z"),
            ),
            "sources": (
                "sm_100a/cake_gdn_chunk_train_52c9eb9acaf6543b11c2_kernel.cu",
                "sm_100a/cake_gdn_chunk_train_52c9eb9acaf6543b11c2_binding.cu",
            ),
            "block": (128, 1, 1),
            "dynamic_smem_bytes": 106752,
            "tma_workspace_bytes": 0,
            "ffi_entry": "run",
            "compile_flags": (),
        },
        "sm_103a": {
            "name": "cake_gdn_chunk_train_ae59cf683cfe08987d14",
            "arch": "sm_103a",
            "cache_name": "cake_gdn_chunk_train_ae59cf683cfe08987d14_sm_103a",
            "kernel_symbol": "kernel_cake_gdn_chunk_train_ae59cf683cfe08987d14",
            "arg_plan": (
                ("buffer", "kn"),
                ("buffer", "w"),
                ("buffer", "u"),
                ("buffer", "g_cs"),
                ("buffer", "h0"),
                ("buffer", "h_out"),
                ("buffer", "v_new"),
                ("buffer", "final_state"),
                ("buffer", "chunk_start"),
                ("buffer", "chunk_len"),
                ("buffer", "seq_chunk_start"),
                ("parameter", "num_heads"),
                ("parameter", "num_v_heads"),
                ("parameter", "use_initial_state"),
                ("parameter", "store_final_state"),
                ("grid", "grid_x"),
                ("grid", "grid_y"),
                ("grid", "grid_z"),
            ),
            "sources": (
                "sm_103a/cake_gdn_chunk_train_ae59cf683cfe08987d14_kernel.cu",
                "sm_103a/cake_gdn_chunk_train_ae59cf683cfe08987d14_binding.cu",
            ),
            "block": (128, 1, 1),
            "dynamic_smem_bytes": 106752,
            "tma_workspace_bytes": 0,
            "ffi_entry": "run",
            "compile_flags": (),
        },
    },
    "fwd_h_v16": {
        "sm_100a": {
            "name": "cake_gdn_chunk_train_d0a2cae4e982e3c58b06",
            "arch": "sm_100a",
            "cache_name": "cake_gdn_chunk_train_d0a2cae4e982e3c58b06_sm_100a",
            "kernel_symbol": "kernel_cake_gdn_chunk_train_d0a2cae4e982e3c58b06",
            "arg_plan": (
                ("buffer", "kn"),
                ("buffer", "w"),
                ("buffer", "u"),
                ("buffer", "g_cs"),
                ("buffer", "h0"),
                ("buffer", "h_out"),
                ("buffer", "v_new"),
                ("buffer", "final_state"),
                ("buffer", "chunk_start"),
                ("buffer", "chunk_len"),
                ("buffer", "seq_chunk_start"),
                ("parameter", "num_heads"),
                ("parameter", "num_v_heads"),
                ("parameter", "use_initial_state"),
                ("parameter", "store_final_state"),
                ("grid", "grid_x"),
                ("grid", "grid_y"),
                ("grid", "grid_z"),
            ),
            "sources": (
                "sm_100a/cake_gdn_chunk_train_d0a2cae4e982e3c58b06_kernel.cu",
                "sm_100a/cake_gdn_chunk_train_d0a2cae4e982e3c58b06_binding.cu",
            ),
            "block": (128, 1, 1),
            "dynamic_smem_bytes": 106752,
            "tma_workspace_bytes": 0,
            "ffi_entry": "run",
            "compile_flags": (),
        },
        "sm_103a": {
            "name": "cake_gdn_chunk_train_61620794a13b00e0ed43",
            "arch": "sm_103a",
            "cache_name": "cake_gdn_chunk_train_61620794a13b00e0ed43_sm_103a",
            "kernel_symbol": "kernel_cake_gdn_chunk_train_61620794a13b00e0ed43",
            "arg_plan": (
                ("buffer", "kn"),
                ("buffer", "w"),
                ("buffer", "u"),
                ("buffer", "g_cs"),
                ("buffer", "h0"),
                ("buffer", "h_out"),
                ("buffer", "v_new"),
                ("buffer", "final_state"),
                ("buffer", "chunk_start"),
                ("buffer", "chunk_len"),
                ("buffer", "seq_chunk_start"),
                ("parameter", "num_heads"),
                ("parameter", "num_v_heads"),
                ("parameter", "use_initial_state"),
                ("parameter", "store_final_state"),
                ("grid", "grid_x"),
                ("grid", "grid_y"),
                ("grid", "grid_z"),
            ),
            "sources": (
                "sm_103a/cake_gdn_chunk_train_61620794a13b00e0ed43_kernel.cu",
                "sm_103a/cake_gdn_chunk_train_61620794a13b00e0ed43_binding.cu",
            ),
            "block": (128, 1, 1),
            "dynamic_smem_bytes": 106752,
            "tma_workspace_bytes": 0,
            "ffi_entry": "run",
            "compile_flags": (),
        },
    },
    "fwd_h_v8": {
        "sm_100a": {
            "name": "cake_gdn_chunk_train_7ebd5bd18f5e2b89560e",
            "arch": "sm_100a",
            "cache_name": "cake_gdn_chunk_train_7ebd5bd18f5e2b89560e_sm_100a",
            "kernel_symbol": "kernel_cake_gdn_chunk_train_7ebd5bd18f5e2b89560e",
            "arg_plan": (
                ("buffer", "kn"),
                ("buffer", "w"),
                ("buffer", "u"),
                ("buffer", "g_cs"),
                ("buffer", "h0"),
                ("buffer", "h_out"),
                ("buffer", "v_new"),
                ("buffer", "final_state"),
                ("buffer", "chunk_start"),
                ("buffer", "chunk_len"),
                ("buffer", "seq_chunk_start"),
                ("parameter", "num_heads"),
                ("parameter", "num_v_heads"),
                ("parameter", "use_initial_state"),
                ("parameter", "store_final_state"),
                ("grid", "grid_x"),
                ("grid", "grid_y"),
                ("grid", "grid_z"),
            ),
            "sources": (
                "sm_100a/cake_gdn_chunk_train_7ebd5bd18f5e2b89560e_kernel.cu",
                "sm_100a/cake_gdn_chunk_train_7ebd5bd18f5e2b89560e_binding.cu",
            ),
            "block": (128, 1, 1),
            "dynamic_smem_bytes": 106752,
            "tma_workspace_bytes": 0,
            "ffi_entry": "run",
            "compile_flags": (),
        },
        "sm_103a": {
            "name": "cake_gdn_chunk_train_ea871f9ef902a58ef47c",
            "arch": "sm_103a",
            "cache_name": "cake_gdn_chunk_train_ea871f9ef902a58ef47c_sm_103a",
            "kernel_symbol": "kernel_cake_gdn_chunk_train_ea871f9ef902a58ef47c",
            "arg_plan": (
                ("buffer", "kn"),
                ("buffer", "w"),
                ("buffer", "u"),
                ("buffer", "g_cs"),
                ("buffer", "h0"),
                ("buffer", "h_out"),
                ("buffer", "v_new"),
                ("buffer", "final_state"),
                ("buffer", "chunk_start"),
                ("buffer", "chunk_len"),
                ("buffer", "seq_chunk_start"),
                ("parameter", "num_heads"),
                ("parameter", "num_v_heads"),
                ("parameter", "use_initial_state"),
                ("parameter", "store_final_state"),
                ("grid", "grid_x"),
                ("grid", "grid_y"),
                ("grid", "grid_z"),
            ),
            "sources": (
                "sm_103a/cake_gdn_chunk_train_ea871f9ef902a58ef47c_kernel.cu",
                "sm_103a/cake_gdn_chunk_train_ea871f9ef902a58ef47c_binding.cu",
            ),
            "block": (128, 1, 1),
            "dynamic_smem_bytes": 106752,
            "tma_workspace_bytes": 0,
            "ffi_entry": "run",
            "compile_flags": (),
        },
    },
    "fwd_h_r32k2": {
        "sm_100a": {
            "name": "cake_gdn_chunk_train_3bb5ea7c18d7965632f7",
            "arch": "sm_100a",
            "cache_name": "cake_gdn_chunk_train_3bb5ea7c18d7965632f7_sm_100a",
            "kernel_symbol": "kernel_cake_gdn_chunk_train_3bb5ea7c18d7965632f7",
            "arg_plan": (
                ("buffer", "kn"),
                ("buffer", "w"),
                ("buffer", "u"),
                ("buffer", "g_cs"),
                ("buffer", "h0"),
                ("buffer", "h_out"),
                ("buffer", "v_new"),
                ("buffer", "final_state"),
                ("buffer", "chunk_start"),
                ("buffer", "chunk_len"),
                ("buffer", "seq_chunk_start"),
                ("parameter", "num_heads"),
                ("parameter", "num_v_heads"),
                ("parameter", "use_initial_state"),
                ("parameter", "store_final_state"),
                ("grid", "grid_x"),
                ("grid", "grid_y"),
                ("grid", "grid_z"),
            ),
            "sources": (
                "sm_100a/cake_gdn_chunk_train_3bb5ea7c18d7965632f7_kernel.cu",
                "sm_100a/cake_gdn_chunk_train_3bb5ea7c18d7965632f7_binding.cu",
            ),
            "block": (128, 1, 1),
            "dynamic_smem_bytes": 107008,
            "tma_workspace_bytes": 0,
            "ffi_entry": "run",
            "compile_flags": (),
        },
        "sm_103a": {
            "name": "cake_gdn_chunk_train_187f5a735170d80d3baa",
            "arch": "sm_103a",
            "cache_name": "cake_gdn_chunk_train_187f5a735170d80d3baa_sm_103a",
            "kernel_symbol": "kernel_cake_gdn_chunk_train_187f5a735170d80d3baa",
            "arg_plan": (
                ("buffer", "kn"),
                ("buffer", "w"),
                ("buffer", "u"),
                ("buffer", "g_cs"),
                ("buffer", "h0"),
                ("buffer", "h_out"),
                ("buffer", "v_new"),
                ("buffer", "final_state"),
                ("buffer", "chunk_start"),
                ("buffer", "chunk_len"),
                ("buffer", "seq_chunk_start"),
                ("parameter", "num_heads"),
                ("parameter", "num_v_heads"),
                ("parameter", "use_initial_state"),
                ("parameter", "store_final_state"),
                ("grid", "grid_x"),
                ("grid", "grid_y"),
                ("grid", "grid_z"),
            ),
            "sources": (
                "sm_103a/cake_gdn_chunk_train_187f5a735170d80d3baa_kernel.cu",
                "sm_103a/cake_gdn_chunk_train_187f5a735170d80d3baa_binding.cu",
            ),
            "block": (128, 1, 1),
            "dynamic_smem_bytes": 107008,
            "tma_workspace_bytes": 0,
            "ffi_entry": "run",
            "compile_flags": (),
        },
    },
    "fwd_h_r32k1": {
        "sm_100a": {
            "name": "cake_gdn_chunk_train_42d87f570cb2ebf9b6c6",
            "arch": "sm_100a",
            "cache_name": "cake_gdn_chunk_train_42d87f570cb2ebf9b6c6_sm_100a",
            "kernel_symbol": "kernel_cake_gdn_chunk_train_42d87f570cb2ebf9b6c6",
            "arg_plan": (
                ("buffer", "kn"),
                ("buffer", "w"),
                ("buffer", "u"),
                ("buffer", "g_cs"),
                ("buffer", "h0"),
                ("buffer", "h_out"),
                ("buffer", "v_new"),
                ("buffer", "final_state"),
                ("buffer", "chunk_start"),
                ("buffer", "chunk_len"),
                ("buffer", "seq_chunk_start"),
                ("parameter", "num_heads"),
                ("parameter", "num_v_heads"),
                ("parameter", "use_initial_state"),
                ("parameter", "store_final_state"),
                ("grid", "grid_x"),
                ("grid", "grid_y"),
                ("grid", "grid_z"),
            ),
            "sources": (
                "sm_100a/cake_gdn_chunk_train_42d87f570cb2ebf9b6c6_kernel.cu",
                "sm_100a/cake_gdn_chunk_train_42d87f570cb2ebf9b6c6_binding.cu",
            ),
            "block": (64, 1, 1),
            "dynamic_smem_bytes": 90752,
            "tma_workspace_bytes": 0,
            "ffi_entry": "run",
            "compile_flags": (),
        },
        "sm_103a": {
            "name": "cake_gdn_chunk_train_0526263b5085f1e26dd3",
            "arch": "sm_103a",
            "cache_name": "cake_gdn_chunk_train_0526263b5085f1e26dd3_sm_103a",
            "kernel_symbol": "kernel_cake_gdn_chunk_train_0526263b5085f1e26dd3",
            "arg_plan": (
                ("buffer", "kn"),
                ("buffer", "w"),
                ("buffer", "u"),
                ("buffer", "g_cs"),
                ("buffer", "h0"),
                ("buffer", "h_out"),
                ("buffer", "v_new"),
                ("buffer", "final_state"),
                ("buffer", "chunk_start"),
                ("buffer", "chunk_len"),
                ("buffer", "seq_chunk_start"),
                ("parameter", "num_heads"),
                ("parameter", "num_v_heads"),
                ("parameter", "use_initial_state"),
                ("parameter", "store_final_state"),
                ("grid", "grid_x"),
                ("grid", "grid_y"),
                ("grid", "grid_z"),
            ),
            "sources": (
                "sm_103a/cake_gdn_chunk_train_0526263b5085f1e26dd3_kernel.cu",
                "sm_103a/cake_gdn_chunk_train_0526263b5085f1e26dd3_binding.cu",
            ),
            "block": (64, 1, 1),
            "dynamic_smem_bytes": 90752,
            "tma_workspace_bytes": 0,
            "ffi_entry": "run",
            "compile_flags": (),
        },
    },
    "fwd_h_r64k1": {
        "sm_100a": {
            "name": "cake_gdn_chunk_train_578831049b4e2cd00eb8",
            "arch": "sm_100a",
            "cache_name": "cake_gdn_chunk_train_578831049b4e2cd00eb8_sm_100a",
            "kernel_symbol": "kernel_cake_gdn_chunk_train_578831049b4e2cd00eb8",
            "arg_plan": (
                ("buffer", "kn"),
                ("buffer", "w"),
                ("buffer", "u"),
                ("buffer", "g_cs"),
                ("buffer", "h0"),
                ("buffer", "h_out"),
                ("buffer", "v_new"),
                ("buffer", "final_state"),
                ("buffer", "chunk_start"),
                ("buffer", "chunk_len"),
                ("buffer", "seq_chunk_start"),
                ("parameter", "num_heads"),
                ("parameter", "num_v_heads"),
                ("parameter", "use_initial_state"),
                ("parameter", "store_final_state"),
                ("grid", "grid_x"),
                ("grid", "grid_y"),
                ("grid", "grid_z"),
            ),
            "sources": (
                "sm_100a/cake_gdn_chunk_train_578831049b4e2cd00eb8_kernel.cu",
                "sm_100a/cake_gdn_chunk_train_578831049b4e2cd00eb8_binding.cu",
            ),
            "block": (128, 1, 1),
            "dynamic_smem_bytes": 98944,
            "tma_workspace_bytes": 0,
            "ffi_entry": "run",
            "compile_flags": (),
        },
        "sm_103a": {
            "name": "cake_gdn_chunk_train_944594b87298f0537d4a",
            "arch": "sm_103a",
            "cache_name": "cake_gdn_chunk_train_944594b87298f0537d4a_sm_103a",
            "kernel_symbol": "kernel_cake_gdn_chunk_train_944594b87298f0537d4a",
            "arg_plan": (
                ("buffer", "kn"),
                ("buffer", "w"),
                ("buffer", "u"),
                ("buffer", "g_cs"),
                ("buffer", "h0"),
                ("buffer", "h_out"),
                ("buffer", "v_new"),
                ("buffer", "final_state"),
                ("buffer", "chunk_start"),
                ("buffer", "chunk_len"),
                ("buffer", "seq_chunk_start"),
                ("parameter", "num_heads"),
                ("parameter", "num_v_heads"),
                ("parameter", "use_initial_state"),
                ("parameter", "store_final_state"),
                ("grid", "grid_x"),
                ("grid", "grid_y"),
                ("grid", "grid_z"),
            ),
            "sources": (
                "sm_103a/cake_gdn_chunk_train_944594b87298f0537d4a_kernel.cu",
                "sm_103a/cake_gdn_chunk_train_944594b87298f0537d4a_binding.cu",
            ),
            "block": (128, 1, 1),
            "dynamic_smem_bytes": 98944,
            "tma_workspace_bytes": 0,
            "ffi_entry": "run",
            "compile_flags": (),
        },
    },
    "dv_local": {
        "sm_100a": {
            "name": "cake_gdn_chunk_train_69c45c2c625104cdf3a0",
            "arch": "sm_100a",
            "cache_name": "cake_gdn_chunk_train_69c45c2c625104cdf3a0_sm_100a",
            "kernel_symbol": "kernel_cake_gdn_chunk_train_69c45c2c625104cdf3a0",
            "arg_plan": (
                ("buffer", "qn"),
                ("buffer", "kn"),
                ("buffer", "do"),
                ("buffer", "g_cs"),
                ("buffer", "dv_local"),
                ("buffer", "chunk_start"),
                ("buffer", "chunk_len"),
                ("parameter", "num_heads"),
                ("parameter", "num_v_heads"),
                ("parameter", "scale"),
                ("grid", "grid_x"),
                ("grid", "grid_y"),
                ("grid", "grid_z"),
            ),
            "sources": (
                "sm_100a/cake_gdn_chunk_train_69c45c2c625104cdf3a0_kernel.cu",
                "sm_100a/cake_gdn_chunk_train_69c45c2c625104cdf3a0_binding.cu",
            ),
            "block": (128, 1, 1),
            "dynamic_smem_bytes": 57600,
            "tma_workspace_bytes": 0,
            "ffi_entry": "run",
            "compile_flags": (),
        },
        "sm_103a": {
            "name": "cake_gdn_chunk_train_be25aae8b4c4194a3b4f",
            "arch": "sm_103a",
            "cache_name": "cake_gdn_chunk_train_be25aae8b4c4194a3b4f_sm_103a",
            "kernel_symbol": "kernel_cake_gdn_chunk_train_be25aae8b4c4194a3b4f",
            "arg_plan": (
                ("buffer", "qn"),
                ("buffer", "kn"),
                ("buffer", "do"),
                ("buffer", "g_cs"),
                ("buffer", "dv_local"),
                ("buffer", "chunk_start"),
                ("buffer", "chunk_len"),
                ("parameter", "num_heads"),
                ("parameter", "num_v_heads"),
                ("parameter", "scale"),
                ("grid", "grid_x"),
                ("grid", "grid_y"),
                ("grid", "grid_z"),
            ),
            "sources": (
                "sm_103a/cake_gdn_chunk_train_be25aae8b4c4194a3b4f_kernel.cu",
                "sm_103a/cake_gdn_chunk_train_be25aae8b4c4194a3b4f_binding.cu",
            ),
            "block": (128, 1, 1),
            "dynamic_smem_bytes": 57600,
            "tma_workspace_bytes": 0,
            "ffi_entry": "run",
            "compile_flags": (),
        },
    },
    "dhu": {
        "sm_100a": {
            "name": "cake_gdn_chunk_train_42790db822224eb17620",
            "arch": "sm_100a",
            "cache_name": "cake_gdn_chunk_train_42790db822224eb17620_sm_100a",
            "kernel_symbol": "kernel_cake_gdn_chunk_train_42790db822224eb17620",
            "arg_plan": (
                ("buffer", "qn"),
                ("buffer", "kn"),
                ("buffer", "w"),
                ("buffer", "do"),
                ("buffer", "dv_local"),
                ("buffer", "g_cs"),
                ("buffer", "dht"),
                ("buffer", "dh_out"),
                ("buffer", "dv2"),
                ("buffer", "dh0"),
                ("buffer", "chunk_start"),
                ("buffer", "chunk_len"),
                ("buffer", "seq_chunk_start"),
                ("parameter", "num_heads"),
                ("parameter", "num_v_heads"),
                ("parameter", "use_final_state_grad"),
                ("parameter", "store_initial_state_grad"),
                ("parameter", "scale"),
                ("grid", "grid_x"),
                ("grid", "grid_y"),
                ("grid", "grid_z"),
            ),
            "sources": (
                "sm_100a/cake_gdn_chunk_train_42790db822224eb17620_kernel.cu",
                "sm_100a/cake_gdn_chunk_train_42790db822224eb17620_binding.cu",
            ),
            "block": (128, 1, 1),
            "dynamic_smem_bytes": 164096,
            "tma_workspace_bytes": 0,
            "ffi_entry": "run",
            "compile_flags": (),
        },
        "sm_103a": {
            "name": "cake_gdn_chunk_train_24c55cd0e205111d2d9a",
            "arch": "sm_103a",
            "cache_name": "cake_gdn_chunk_train_24c55cd0e205111d2d9a_sm_103a",
            "kernel_symbol": "kernel_cake_gdn_chunk_train_24c55cd0e205111d2d9a",
            "arg_plan": (
                ("buffer", "qn"),
                ("buffer", "kn"),
                ("buffer", "w"),
                ("buffer", "do"),
                ("buffer", "dv_local"),
                ("buffer", "g_cs"),
                ("buffer", "dht"),
                ("buffer", "dh_out"),
                ("buffer", "dv2"),
                ("buffer", "dh0"),
                ("buffer", "chunk_start"),
                ("buffer", "chunk_len"),
                ("buffer", "seq_chunk_start"),
                ("parameter", "num_heads"),
                ("parameter", "num_v_heads"),
                ("parameter", "use_final_state_grad"),
                ("parameter", "store_initial_state_grad"),
                ("parameter", "scale"),
                ("grid", "grid_x"),
                ("grid", "grid_y"),
                ("grid", "grid_z"),
            ),
            "sources": (
                "sm_103a/cake_gdn_chunk_train_24c55cd0e205111d2d9a_kernel.cu",
                "sm_103a/cake_gdn_chunk_train_24c55cd0e205111d2d9a_binding.cu",
            ),
            "block": (128, 1, 1),
            "dynamic_smem_bytes": 164096,
            "tma_workspace_bytes": 0,
            "ffi_entry": "run",
            "compile_flags": (),
        },
    },
    "dqkwg": {
        "sm_100a": {
            "name": "cake_gdn_chunk_train_44a7dd7b3a6d3f0b0045",
            "arch": "sm_100a",
            "cache_name": "cake_gdn_chunk_train_44a7dd7b3a6d3f0b0045_sm_100a",
            "kernel_symbol": "kernel_cake_gdn_chunk_train_44a7dd7b3a6d3f0b0045",
            "arg_plan": (
                ("buffer", "qn"),
                ("buffer", "kn"),
                ("buffer", "v_new"),
                ("buffer", "do"),
                ("buffer", "dv2"),
                ("buffer", "h"),
                ("buffer", "dh"),
                ("buffer", "g_cs"),
                ("buffer", "dq_out"),
                ("buffer", "dk_out"),
                ("buffer", "dw_out"),
                ("buffer", "dg_out"),
                ("buffer", "chunk_start"),
                ("buffer", "chunk_len"),
                ("parameter", "num_heads"),
                ("parameter", "num_v_heads"),
                ("parameter", "scale"),
                ("grid", "grid_x"),
                ("grid", "grid_y"),
                ("grid", "grid_z"),
            ),
            "sources": (
                "sm_100a/cake_gdn_chunk_train_44a7dd7b3a6d3f0b0045_kernel.cu",
                "sm_100a/cake_gdn_chunk_train_44a7dd7b3a6d3f0b0045_binding.cu",
            ),
            "block": (128, 1, 1),
            "dynamic_smem_bytes": 156928,
            "tma_workspace_bytes": 0,
            "ffi_entry": "run",
            "compile_flags": (),
        },
        "sm_103a": {
            "name": "cake_gdn_chunk_train_6d7c261b3ab8339ea352",
            "arch": "sm_103a",
            "cache_name": "cake_gdn_chunk_train_6d7c261b3ab8339ea352_sm_103a",
            "kernel_symbol": "kernel_cake_gdn_chunk_train_6d7c261b3ab8339ea352",
            "arg_plan": (
                ("buffer", "qn"),
                ("buffer", "kn"),
                ("buffer", "v_new"),
                ("buffer", "do"),
                ("buffer", "dv2"),
                ("buffer", "h"),
                ("buffer", "dh"),
                ("buffer", "g_cs"),
                ("buffer", "dq_out"),
                ("buffer", "dk_out"),
                ("buffer", "dw_out"),
                ("buffer", "dg_out"),
                ("buffer", "chunk_start"),
                ("buffer", "chunk_len"),
                ("parameter", "num_heads"),
                ("parameter", "num_v_heads"),
                ("parameter", "scale"),
                ("grid", "grid_x"),
                ("grid", "grid_y"),
                ("grid", "grid_z"),
            ),
            "sources": (
                "sm_103a/cake_gdn_chunk_train_6d7c261b3ab8339ea352_kernel.cu",
                "sm_103a/cake_gdn_chunk_train_6d7c261b3ab8339ea352_binding.cu",
            ),
            "block": (128, 1, 1),
            "dynamic_smem_bytes": 156928,
            "tma_workspace_bytes": 0,
            "ffi_entry": "run",
            "compile_flags": (),
        },
    },
    "wy_bwd": {
        "sm_100a": {
            "name": "cake_gdn_chunk_train_08b8c467d9dd75bd69d7",
            "arch": "sm_100a",
            "cache_name": "cake_gdn_chunk_train_08b8c467d9dd75bd69d7_sm_100a",
            "kernel_symbol": "kernel_cake_gdn_chunk_train_08b8c467d9dd75bd69d7",
            "arg_plan": (
                ("buffer", "kn"),
                ("buffer", "v"),
                ("buffer", "A"),
                ("buffer", "dw"),
                ("buffer", "du"),
                ("buffer", "g_cs"),
                ("buffer", "beta"),
                ("buffer", "dk2_out"),
                ("buffer", "dv_out"),
                ("buffer", "dbeta_out"),
                ("buffer", "dg2_out"),
                ("buffer", "chunk_start"),
                ("buffer", "chunk_len"),
                ("parameter", "num_heads"),
                ("parameter", "num_v_heads"),
                ("grid", "grid_x"),
                ("grid", "grid_y"),
                ("grid", "grid_z"),
            ),
            "sources": (
                "sm_100a/cake_gdn_chunk_train_08b8c467d9dd75bd69d7_kernel.cu",
                "sm_100a/cake_gdn_chunk_train_08b8c467d9dd75bd69d7_binding.cu",
            ),
            "block": (128, 1, 1),
            "dynamic_smem_bytes": 108032,
            "tma_workspace_bytes": 0,
            "ffi_entry": "run",
            "compile_flags": (),
        },
        "sm_103a": {
            "name": "cake_gdn_chunk_train_e3fcd8f17111bef4a95b",
            "arch": "sm_103a",
            "cache_name": "cake_gdn_chunk_train_e3fcd8f17111bef4a95b_sm_103a",
            "kernel_symbol": "kernel_cake_gdn_chunk_train_e3fcd8f17111bef4a95b",
            "arg_plan": (
                ("buffer", "kn"),
                ("buffer", "v"),
                ("buffer", "A"),
                ("buffer", "dw"),
                ("buffer", "du"),
                ("buffer", "g_cs"),
                ("buffer", "beta"),
                ("buffer", "dk2_out"),
                ("buffer", "dv_out"),
                ("buffer", "dbeta_out"),
                ("buffer", "dg2_out"),
                ("buffer", "chunk_start"),
                ("buffer", "chunk_len"),
                ("parameter", "num_heads"),
                ("parameter", "num_v_heads"),
                ("grid", "grid_x"),
                ("grid", "grid_y"),
                ("grid", "grid_z"),
            ),
            "sources": (
                "sm_103a/cake_gdn_chunk_train_e3fcd8f17111bef4a95b_kernel.cu",
                "sm_103a/cake_gdn_chunk_train_e3fcd8f17111bef4a95b_binding.cu",
            ),
            "block": (128, 1, 1),
            "dynamic_smem_bytes": 108032,
            "tma_workspace_bytes": 0,
            "ffi_entry": "run",
            "compile_flags": (),
        },
    },
    "wy_bwd_bf16": {
        "sm_100a": {
            "name": "cake_gdn_chunk_train_c2d8e02001feb945f994",
            "arch": "sm_100a",
            "cache_name": "cake_gdn_chunk_train_c2d8e02001feb945f994_sm_100a",
            "kernel_symbol": "kernel_cake_gdn_chunk_train_c2d8e02001feb945f994",
            "arg_plan": (
                ("buffer", "kn"),
                ("buffer", "v"),
                ("buffer", "A"),
                ("buffer", "dw"),
                ("buffer", "du"),
                ("buffer", "g_cs"),
                ("buffer", "beta"),
                ("buffer", "dk2_out"),
                ("buffer", "dv_out"),
                ("buffer", "dbeta_out"),
                ("buffer", "dg2_out"),
                ("buffer", "chunk_start"),
                ("buffer", "chunk_len"),
                ("parameter", "num_heads"),
                ("parameter", "num_v_heads"),
                ("grid", "grid_x"),
                ("grid", "grid_y"),
                ("grid", "grid_z"),
            ),
            "sources": (
                "sm_100a/cake_gdn_chunk_train_c2d8e02001feb945f994_kernel.cu",
                "sm_100a/cake_gdn_chunk_train_c2d8e02001feb945f994_binding.cu",
            ),
            "block": (128, 1, 1),
            "dynamic_smem_bytes": 108032,
            "tma_workspace_bytes": 0,
            "ffi_entry": "run",
            "compile_flags": (),
        },
        "sm_103a": {
            "name": "cake_gdn_chunk_train_d73e6fff48ee4ff5af4a",
            "arch": "sm_103a",
            "cache_name": "cake_gdn_chunk_train_d73e6fff48ee4ff5af4a_sm_103a",
            "kernel_symbol": "kernel_cake_gdn_chunk_train_d73e6fff48ee4ff5af4a",
            "arg_plan": (
                ("buffer", "kn"),
                ("buffer", "v"),
                ("buffer", "A"),
                ("buffer", "dw"),
                ("buffer", "du"),
                ("buffer", "g_cs"),
                ("buffer", "beta"),
                ("buffer", "dk2_out"),
                ("buffer", "dv_out"),
                ("buffer", "dbeta_out"),
                ("buffer", "dg2_out"),
                ("buffer", "chunk_start"),
                ("buffer", "chunk_len"),
                ("parameter", "num_heads"),
                ("parameter", "num_v_heads"),
                ("grid", "grid_x"),
                ("grid", "grid_y"),
                ("grid", "grid_z"),
            ),
            "sources": (
                "sm_103a/cake_gdn_chunk_train_d73e6fff48ee4ff5af4a_kernel.cu",
                "sm_103a/cake_gdn_chunk_train_d73e6fff48ee4ff5af4a_binding.cu",
            ),
            "block": (128, 1, 1),
            "dynamic_smem_bytes": 108032,
            "tma_workspace_bytes": 0,
            "ffi_entry": "run",
            "compile_flags": (),
        },
    },
    "finalize": {
        "sm_100a": {
            "name": "cake_gdn_chunk_train_f476781e557972f034c5",
            "arch": "sm_100a",
            "cache_name": "cake_gdn_chunk_train_f476781e557972f034c5_sm_100a",
            "kernel_symbol": "kernel_cake_gdn_chunk_train_f476781e557972f034c5",
            "arg_plan": (
                ("buffer", "qn"),
                ("buffer", "kn"),
                ("buffer", "rstd_q"),
                ("buffer", "rstd_k"),
                ("buffer", "dq_hv"),
                ("buffer", "dk_hv"),
                ("buffer", "dk2"),
                ("buffer", "dg1"),
                ("buffer", "dg2"),
                ("buffer", "dq_out"),
                ("buffer", "dk_out"),
                ("buffer", "dg_out"),
                ("buffer", "chunk_start"),
                ("buffer", "chunk_len"),
                ("parameter", "num_heads"),
                ("parameter", "num_v_heads"),
                ("parameter", "normalize_qk"),
                ("grid", "grid_x"),
                ("grid", "grid_y"),
                ("grid", "grid_z"),
            ),
            "sources": (
                "sm_100a/cake_gdn_chunk_train_f476781e557972f034c5_kernel.cu",
                "sm_100a/cake_gdn_chunk_train_f476781e557972f034c5_binding.cu",
            ),
            "block": (128, 1, 1),
            "dynamic_smem_bytes": 0,
            "tma_workspace_bytes": 0,
            "ffi_entry": "run",
            "compile_flags": (),
        },
        "sm_103a": {
            "name": "cake_gdn_chunk_train_4423345a9505351dc8de",
            "arch": "sm_103a",
            "cache_name": "cake_gdn_chunk_train_4423345a9505351dc8de_sm_103a",
            "kernel_symbol": "kernel_cake_gdn_chunk_train_4423345a9505351dc8de",
            "arg_plan": (
                ("buffer", "qn"),
                ("buffer", "kn"),
                ("buffer", "rstd_q"),
                ("buffer", "rstd_k"),
                ("buffer", "dq_hv"),
                ("buffer", "dk_hv"),
                ("buffer", "dk2"),
                ("buffer", "dg1"),
                ("buffer", "dg2"),
                ("buffer", "dq_out"),
                ("buffer", "dk_out"),
                ("buffer", "dg_out"),
                ("buffer", "chunk_start"),
                ("buffer", "chunk_len"),
                ("parameter", "num_heads"),
                ("parameter", "num_v_heads"),
                ("parameter", "normalize_qk"),
                ("grid", "grid_x"),
                ("grid", "grid_y"),
                ("grid", "grid_z"),
            ),
            "sources": (
                "sm_103a/cake_gdn_chunk_train_4423345a9505351dc8de_kernel.cu",
                "sm_103a/cake_gdn_chunk_train_4423345a9505351dc8de_binding.cu",
            ),
            "block": (128, 1, 1),
            "dynamic_smem_bytes": 0,
            "tma_workspace_bytes": 0,
            "ffi_entry": "run",
            "compile_flags": (),
        },
    },
    "dhu_v64": {
        "sm_100a": {
            "name": "cake_gdn_chunk_train_42790db822224eb17620",
            "arch": "sm_100a",
            "cache_name": "cake_gdn_chunk_train_42790db822224eb17620_sm_100a",
            "kernel_symbol": "kernel_cake_gdn_chunk_train_42790db822224eb17620",
            "arg_plan": (
                ("buffer", "qn"),
                ("buffer", "kn"),
                ("buffer", "w"),
                ("buffer", "do"),
                ("buffer", "dv_local"),
                ("buffer", "g_cs"),
                ("buffer", "dht"),
                ("buffer", "dh_out"),
                ("buffer", "dv2"),
                ("buffer", "dh0"),
                ("buffer", "chunk_start"),
                ("buffer", "chunk_len"),
                ("buffer", "seq_chunk_start"),
                ("parameter", "num_heads"),
                ("parameter", "num_v_heads"),
                ("parameter", "use_final_state_grad"),
                ("parameter", "store_initial_state_grad"),
                ("parameter", "scale"),
                ("grid", "grid_x"),
                ("grid", "grid_y"),
                ("grid", "grid_z"),
            ),
            "sources": (
                "sm_100a/cake_gdn_chunk_train_42790db822224eb17620_kernel.cu",
                "sm_100a/cake_gdn_chunk_train_42790db822224eb17620_binding.cu",
            ),
            "block": (128, 1, 1),
            "dynamic_smem_bytes": 164096,
            "tma_workspace_bytes": 0,
            "ffi_entry": "run",
            "compile_flags": (),
        },
        "sm_103a": {
            "name": "cake_gdn_chunk_train_24c55cd0e205111d2d9a",
            "arch": "sm_103a",
            "cache_name": "cake_gdn_chunk_train_24c55cd0e205111d2d9a_sm_103a",
            "kernel_symbol": "kernel_cake_gdn_chunk_train_24c55cd0e205111d2d9a",
            "arg_plan": (
                ("buffer", "qn"),
                ("buffer", "kn"),
                ("buffer", "w"),
                ("buffer", "do"),
                ("buffer", "dv_local"),
                ("buffer", "g_cs"),
                ("buffer", "dht"),
                ("buffer", "dh_out"),
                ("buffer", "dv2"),
                ("buffer", "dh0"),
                ("buffer", "chunk_start"),
                ("buffer", "chunk_len"),
                ("buffer", "seq_chunk_start"),
                ("parameter", "num_heads"),
                ("parameter", "num_v_heads"),
                ("parameter", "use_final_state_grad"),
                ("parameter", "store_initial_state_grad"),
                ("parameter", "scale"),
                ("grid", "grid_x"),
                ("grid", "grid_y"),
                ("grid", "grid_z"),
            ),
            "sources": (
                "sm_103a/cake_gdn_chunk_train_24c55cd0e205111d2d9a_kernel.cu",
                "sm_103a/cake_gdn_chunk_train_24c55cd0e205111d2d9a_binding.cu",
            ),
            "block": (128, 1, 1),
            "dynamic_smem_bytes": 164096,
            "tma_workspace_bytes": 0,
            "ffi_entry": "run",
            "compile_flags": (),
        },
    },
    "dhu_v32": {
        "sm_100a": {
            "name": "cake_gdn_chunk_train_71cbe90da1adda86f721",
            "arch": "sm_100a",
            "cache_name": "cake_gdn_chunk_train_71cbe90da1adda86f721_sm_100a",
            "kernel_symbol": "kernel_cake_gdn_chunk_train_71cbe90da1adda86f721",
            "arg_plan": (
                ("buffer", "qn"),
                ("buffer", "kn"),
                ("buffer", "w"),
                ("buffer", "do"),
                ("buffer", "dv_local"),
                ("buffer", "g_cs"),
                ("buffer", "dht"),
                ("buffer", "dh_out"),
                ("buffer", "dv2"),
                ("buffer", "dh0"),
                ("buffer", "chunk_start"),
                ("buffer", "chunk_len"),
                ("buffer", "seq_chunk_start"),
                ("parameter", "num_heads"),
                ("parameter", "num_v_heads"),
                ("parameter", "use_final_state_grad"),
                ("parameter", "store_initial_state_grad"),
                ("parameter", "scale"),
                ("grid", "grid_x"),
                ("grid", "grid_y"),
                ("grid", "grid_z"),
            ),
            "sources": (
                "sm_100a/cake_gdn_chunk_train_71cbe90da1adda86f721_kernel.cu",
                "sm_100a/cake_gdn_chunk_train_71cbe90da1adda86f721_binding.cu",
            ),
            "block": (128, 1, 1),
            "dynamic_smem_bytes": 164096,
            "tma_workspace_bytes": 0,
            "ffi_entry": "run",
            "compile_flags": (),
        },
        "sm_103a": {
            "name": "cake_gdn_chunk_train_3b9fbe549962757fc024",
            "arch": "sm_103a",
            "cache_name": "cake_gdn_chunk_train_3b9fbe549962757fc024_sm_103a",
            "kernel_symbol": "kernel_cake_gdn_chunk_train_3b9fbe549962757fc024",
            "arg_plan": (
                ("buffer", "qn"),
                ("buffer", "kn"),
                ("buffer", "w"),
                ("buffer", "do"),
                ("buffer", "dv_local"),
                ("buffer", "g_cs"),
                ("buffer", "dht"),
                ("buffer", "dh_out"),
                ("buffer", "dv2"),
                ("buffer", "dh0"),
                ("buffer", "chunk_start"),
                ("buffer", "chunk_len"),
                ("buffer", "seq_chunk_start"),
                ("parameter", "num_heads"),
                ("parameter", "num_v_heads"),
                ("parameter", "use_final_state_grad"),
                ("parameter", "store_initial_state_grad"),
                ("parameter", "scale"),
                ("grid", "grid_x"),
                ("grid", "grid_y"),
                ("grid", "grid_z"),
            ),
            "sources": (
                "sm_103a/cake_gdn_chunk_train_3b9fbe549962757fc024_kernel.cu",
                "sm_103a/cake_gdn_chunk_train_3b9fbe549962757fc024_binding.cu",
            ),
            "block": (128, 1, 1),
            "dynamic_smem_bytes": 164096,
            "tma_workspace_bytes": 0,
            "ffi_entry": "run",
            "compile_flags": (),
        },
    },
    "dhu_v16": {
        "sm_100a": {
            "name": "cake_gdn_chunk_train_86eb0d798fa3a28337ed",
            "arch": "sm_100a",
            "cache_name": "cake_gdn_chunk_train_86eb0d798fa3a28337ed_sm_100a",
            "kernel_symbol": "kernel_cake_gdn_chunk_train_86eb0d798fa3a28337ed",
            "arg_plan": (
                ("buffer", "qn"),
                ("buffer", "kn"),
                ("buffer", "w"),
                ("buffer", "do"),
                ("buffer", "dv_local"),
                ("buffer", "g_cs"),
                ("buffer", "dht"),
                ("buffer", "dh_out"),
                ("buffer", "dv2"),
                ("buffer", "dh0"),
                ("buffer", "chunk_start"),
                ("buffer", "chunk_len"),
                ("buffer", "seq_chunk_start"),
                ("parameter", "num_heads"),
                ("parameter", "num_v_heads"),
                ("parameter", "use_final_state_grad"),
                ("parameter", "store_initial_state_grad"),
                ("parameter", "scale"),
                ("grid", "grid_x"),
                ("grid", "grid_y"),
                ("grid", "grid_z"),
            ),
            "sources": (
                "sm_100a/cake_gdn_chunk_train_86eb0d798fa3a28337ed_kernel.cu",
                "sm_100a/cake_gdn_chunk_train_86eb0d798fa3a28337ed_binding.cu",
            ),
            "block": (128, 1, 1),
            "dynamic_smem_bytes": 164096,
            "tma_workspace_bytes": 0,
            "ffi_entry": "run",
            "compile_flags": (),
        },
        "sm_103a": {
            "name": "cake_gdn_chunk_train_d56f1d662cf8b953aadd",
            "arch": "sm_103a",
            "cache_name": "cake_gdn_chunk_train_d56f1d662cf8b953aadd_sm_103a",
            "kernel_symbol": "kernel_cake_gdn_chunk_train_d56f1d662cf8b953aadd",
            "arg_plan": (
                ("buffer", "qn"),
                ("buffer", "kn"),
                ("buffer", "w"),
                ("buffer", "do"),
                ("buffer", "dv_local"),
                ("buffer", "g_cs"),
                ("buffer", "dht"),
                ("buffer", "dh_out"),
                ("buffer", "dv2"),
                ("buffer", "dh0"),
                ("buffer", "chunk_start"),
                ("buffer", "chunk_len"),
                ("buffer", "seq_chunk_start"),
                ("parameter", "num_heads"),
                ("parameter", "num_v_heads"),
                ("parameter", "use_final_state_grad"),
                ("parameter", "store_initial_state_grad"),
                ("parameter", "scale"),
                ("grid", "grid_x"),
                ("grid", "grid_y"),
                ("grid", "grid_z"),
            ),
            "sources": (
                "sm_103a/cake_gdn_chunk_train_d56f1d662cf8b953aadd_kernel.cu",
                "sm_103a/cake_gdn_chunk_train_d56f1d662cf8b953aadd_binding.cu",
            ),
            "block": (128, 1, 1),
            "dynamic_smem_bytes": 164096,
            "tma_workspace_bytes": 0,
            "ffi_entry": "run",
            "compile_flags": (),
        },
    },
    "dhu_v8": {
        "sm_100a": {
            "name": "cake_gdn_chunk_train_1bbc67313d5ee9a36ce9",
            "arch": "sm_100a",
            "cache_name": "cake_gdn_chunk_train_1bbc67313d5ee9a36ce9_sm_100a",
            "kernel_symbol": "kernel_cake_gdn_chunk_train_1bbc67313d5ee9a36ce9",
            "arg_plan": (
                ("buffer", "qn"),
                ("buffer", "kn"),
                ("buffer", "w"),
                ("buffer", "do"),
                ("buffer", "dv_local"),
                ("buffer", "g_cs"),
                ("buffer", "dht"),
                ("buffer", "dh_out"),
                ("buffer", "dv2"),
                ("buffer", "dh0"),
                ("buffer", "chunk_start"),
                ("buffer", "chunk_len"),
                ("buffer", "seq_chunk_start"),
                ("parameter", "num_heads"),
                ("parameter", "num_v_heads"),
                ("parameter", "use_final_state_grad"),
                ("parameter", "store_initial_state_grad"),
                ("parameter", "scale"),
                ("grid", "grid_x"),
                ("grid", "grid_y"),
                ("grid", "grid_z"),
            ),
            "sources": (
                "sm_100a/cake_gdn_chunk_train_1bbc67313d5ee9a36ce9_kernel.cu",
                "sm_100a/cake_gdn_chunk_train_1bbc67313d5ee9a36ce9_binding.cu",
            ),
            "block": (128, 1, 1),
            "dynamic_smem_bytes": 164096,
            "tma_workspace_bytes": 0,
            "ffi_entry": "run",
            "compile_flags": (),
        },
        "sm_103a": {
            "name": "cake_gdn_chunk_train_3d726f469f6ccbca0bf1",
            "arch": "sm_103a",
            "cache_name": "cake_gdn_chunk_train_3d726f469f6ccbca0bf1_sm_103a",
            "kernel_symbol": "kernel_cake_gdn_chunk_train_3d726f469f6ccbca0bf1",
            "arg_plan": (
                ("buffer", "qn"),
                ("buffer", "kn"),
                ("buffer", "w"),
                ("buffer", "do"),
                ("buffer", "dv_local"),
                ("buffer", "g_cs"),
                ("buffer", "dht"),
                ("buffer", "dh_out"),
                ("buffer", "dv2"),
                ("buffer", "dh0"),
                ("buffer", "chunk_start"),
                ("buffer", "chunk_len"),
                ("buffer", "seq_chunk_start"),
                ("parameter", "num_heads"),
                ("parameter", "num_v_heads"),
                ("parameter", "use_final_state_grad"),
                ("parameter", "store_initial_state_grad"),
                ("parameter", "scale"),
                ("grid", "grid_x"),
                ("grid", "grid_y"),
                ("grid", "grid_z"),
            ),
            "sources": (
                "sm_103a/cake_gdn_chunk_train_3d726f469f6ccbca0bf1_kernel.cu",
                "sm_103a/cake_gdn_chunk_train_3d726f469f6ccbca0bf1_binding.cu",
            ),
            "block": (128, 1, 1),
            "dynamic_smem_bytes": 164096,
            "tma_workspace_bytes": 0,
            "ffi_entry": "run",
            "compile_flags": (),
        },
    },
    "dhu_r32k2": {
        "sm_100a": {
            "name": "cake_gdn_chunk_train_ca87cd15d7b61a97ecde",
            "arch": "sm_100a",
            "cache_name": "cake_gdn_chunk_train_ca87cd15d7b61a97ecde_sm_100a",
            "kernel_symbol": "kernel_cake_gdn_chunk_train_ca87cd15d7b61a97ecde",
            "arg_plan": (
                ("buffer", "qn"),
                ("buffer", "kn"),
                ("buffer", "w"),
                ("buffer", "do"),
                ("buffer", "dv_local"),
                ("buffer", "g_cs"),
                ("buffer", "dht"),
                ("buffer", "dh_out"),
                ("buffer", "dv2"),
                ("buffer", "dh0"),
                ("buffer", "chunk_start"),
                ("buffer", "chunk_len"),
                ("buffer", "seq_chunk_start"),
                ("parameter", "num_heads"),
                ("parameter", "num_v_heads"),
                ("parameter", "use_final_state_grad"),
                ("parameter", "store_initial_state_grad"),
                ("parameter", "scale"),
                ("grid", "grid_x"),
                ("grid", "grid_y"),
                ("grid", "grid_z"),
            ),
            "sources": (
                "sm_100a/cake_gdn_chunk_train_ca87cd15d7b61a97ecde_kernel.cu",
                "sm_100a/cake_gdn_chunk_train_ca87cd15d7b61a97ecde_binding.cu",
            ),
            "block": (128, 1, 1),
            "dynamic_smem_bytes": 156672,
            "tma_workspace_bytes": 0,
            "ffi_entry": "run",
            "compile_flags": (),
        },
        "sm_103a": {
            "name": "cake_gdn_chunk_train_e608f79e7167b9a5dd58",
            "arch": "sm_103a",
            "cache_name": "cake_gdn_chunk_train_e608f79e7167b9a5dd58_sm_103a",
            "kernel_symbol": "kernel_cake_gdn_chunk_train_e608f79e7167b9a5dd58",
            "arg_plan": (
                ("buffer", "qn"),
                ("buffer", "kn"),
                ("buffer", "w"),
                ("buffer", "do"),
                ("buffer", "dv_local"),
                ("buffer", "g_cs"),
                ("buffer", "dht"),
                ("buffer", "dh_out"),
                ("buffer", "dv2"),
                ("buffer", "dh0"),
                ("buffer", "chunk_start"),
                ("buffer", "chunk_len"),
                ("buffer", "seq_chunk_start"),
                ("parameter", "num_heads"),
                ("parameter", "num_v_heads"),
                ("parameter", "use_final_state_grad"),
                ("parameter", "store_initial_state_grad"),
                ("parameter", "scale"),
                ("grid", "grid_x"),
                ("grid", "grid_y"),
                ("grid", "grid_z"),
            ),
            "sources": (
                "sm_103a/cake_gdn_chunk_train_e608f79e7167b9a5dd58_kernel.cu",
                "sm_103a/cake_gdn_chunk_train_e608f79e7167b9a5dd58_binding.cu",
            ),
            "block": (128, 1, 1),
            "dynamic_smem_bytes": 156672,
            "tma_workspace_bytes": 0,
            "ffi_entry": "run",
            "compile_flags": (),
        },
    },
    "dhu_r32k1": {
        "sm_100a": {
            "name": "cake_gdn_chunk_train_e361efceb5efcf4eb52a",
            "arch": "sm_100a",
            "cache_name": "cake_gdn_chunk_train_e361efceb5efcf4eb52a_sm_100a",
            "kernel_symbol": "kernel_cake_gdn_chunk_train_e361efceb5efcf4eb52a",
            "arg_plan": (
                ("buffer", "qn"),
                ("buffer", "kn"),
                ("buffer", "w"),
                ("buffer", "do"),
                ("buffer", "dv_local"),
                ("buffer", "g_cs"),
                ("buffer", "dht"),
                ("buffer", "dh_out"),
                ("buffer", "dv2"),
                ("buffer", "dh0"),
                ("buffer", "chunk_start"),
                ("buffer", "chunk_len"),
                ("buffer", "seq_chunk_start"),
                ("parameter", "num_heads"),
                ("parameter", "num_v_heads"),
                ("parameter", "use_final_state_grad"),
                ("parameter", "store_initial_state_grad"),
                ("parameter", "scale"),
                ("grid", "grid_x"),
                ("grid", "grid_y"),
                ("grid", "grid_z"),
            ),
            "sources": (
                "sm_100a/cake_gdn_chunk_train_e361efceb5efcf4eb52a_kernel.cu",
                "sm_100a/cake_gdn_chunk_train_e361efceb5efcf4eb52a_binding.cu",
            ),
            "block": (64, 1, 1),
            "dynamic_smem_bytes": 140416,
            "tma_workspace_bytes": 0,
            "ffi_entry": "run",
            "compile_flags": (),
        },
        "sm_103a": {
            "name": "cake_gdn_chunk_train_cd78bc68d8a0d531ded7",
            "arch": "sm_103a",
            "cache_name": "cake_gdn_chunk_train_cd78bc68d8a0d531ded7_sm_103a",
            "kernel_symbol": "kernel_cake_gdn_chunk_train_cd78bc68d8a0d531ded7",
            "arg_plan": (
                ("buffer", "qn"),
                ("buffer", "kn"),
                ("buffer", "w"),
                ("buffer", "do"),
                ("buffer", "dv_local"),
                ("buffer", "g_cs"),
                ("buffer", "dht"),
                ("buffer", "dh_out"),
                ("buffer", "dv2"),
                ("buffer", "dh0"),
                ("buffer", "chunk_start"),
                ("buffer", "chunk_len"),
                ("buffer", "seq_chunk_start"),
                ("parameter", "num_heads"),
                ("parameter", "num_v_heads"),
                ("parameter", "use_final_state_grad"),
                ("parameter", "store_initial_state_grad"),
                ("parameter", "scale"),
                ("grid", "grid_x"),
                ("grid", "grid_y"),
                ("grid", "grid_z"),
            ),
            "sources": (
                "sm_103a/cake_gdn_chunk_train_cd78bc68d8a0d531ded7_kernel.cu",
                "sm_103a/cake_gdn_chunk_train_cd78bc68d8a0d531ded7_binding.cu",
            ),
            "block": (64, 1, 1),
            "dynamic_smem_bytes": 140416,
            "tma_workspace_bytes": 0,
            "ffi_entry": "run",
            "compile_flags": (),
        },
    },
    "dhu_r64k1": {
        "sm_100a": {
            "name": "cake_gdn_chunk_train_dea44cbdf6f0e3a36d04",
            "arch": "sm_100a",
            "cache_name": "cake_gdn_chunk_train_dea44cbdf6f0e3a36d04_sm_100a",
            "kernel_symbol": "kernel_cake_gdn_chunk_train_dea44cbdf6f0e3a36d04",
            "arg_plan": (
                ("buffer", "qn"),
                ("buffer", "kn"),
                ("buffer", "w"),
                ("buffer", "do"),
                ("buffer", "dv_local"),
                ("buffer", "g_cs"),
                ("buffer", "dht"),
                ("buffer", "dh_out"),
                ("buffer", "dv2"),
                ("buffer", "dh0"),
                ("buffer", "chunk_start"),
                ("buffer", "chunk_len"),
                ("buffer", "seq_chunk_start"),
                ("parameter", "num_heads"),
                ("parameter", "num_v_heads"),
                ("parameter", "use_final_state_grad"),
                ("parameter", "store_initial_state_grad"),
                ("parameter", "scale"),
                ("grid", "grid_x"),
                ("grid", "grid_y"),
                ("grid", "grid_z"),
            ),
            "sources": (
                "sm_100a/cake_gdn_chunk_train_dea44cbdf6f0e3a36d04_kernel.cu",
                "sm_100a/cake_gdn_chunk_train_dea44cbdf6f0e3a36d04_binding.cu",
            ),
            "block": (128, 1, 1),
            "dynamic_smem_bytes": 148608,
            "tma_workspace_bytes": 0,
            "ffi_entry": "run",
            "compile_flags": (),
        },
        "sm_103a": {
            "name": "cake_gdn_chunk_train_bcaa1b574e81e2aa69a2",
            "arch": "sm_103a",
            "cache_name": "cake_gdn_chunk_train_bcaa1b574e81e2aa69a2_sm_103a",
            "kernel_symbol": "kernel_cake_gdn_chunk_train_bcaa1b574e81e2aa69a2",
            "arg_plan": (
                ("buffer", "qn"),
                ("buffer", "kn"),
                ("buffer", "w"),
                ("buffer", "do"),
                ("buffer", "dv_local"),
                ("buffer", "g_cs"),
                ("buffer", "dht"),
                ("buffer", "dh_out"),
                ("buffer", "dv2"),
                ("buffer", "dh0"),
                ("buffer", "chunk_start"),
                ("buffer", "chunk_len"),
                ("buffer", "seq_chunk_start"),
                ("parameter", "num_heads"),
                ("parameter", "num_v_heads"),
                ("parameter", "use_final_state_grad"),
                ("parameter", "store_initial_state_grad"),
                ("parameter", "scale"),
                ("grid", "grid_x"),
                ("grid", "grid_y"),
                ("grid", "grid_z"),
            ),
            "sources": (
                "sm_103a/cake_gdn_chunk_train_bcaa1b574e81e2aa69a2_kernel.cu",
                "sm_103a/cake_gdn_chunk_train_bcaa1b574e81e2aa69a2_binding.cu",
            ),
            "block": (128, 1, 1),
            "dynamic_smem_bytes": 148608,
            "tma_workspace_bytes": 0,
            "ffi_entry": "run",
            "compile_flags": (),
        },
    },
}


def device_arch(device=None):
    """Map the current CUDA device to the exported architecture tag."""
    capability = torch.cuda.get_device_capability(device)
    try:
        return SUPPORTED_CAPABILITIES[capability]
    except KeyError:
        raise NotImplementedError(f"the deterministic chunked GDN training kernels require SM100a or SM103a, got {capability}") from None


@cache
def load(stage, arch):
    """Build (once per extension cache) and import the native module for ``stage`` on ``arch``."""
    from torch.utils.cpp_extension import load as load_extension

    record = MODULES[stage][arch]
    return load_extension(
        name=record["cache_name"],
        sources=[str(_CSRC / relative) for relative in record["sources"]],
        extra_include_paths=[str(_CSRC)],
        extra_cuda_cflags=[_ARCH_FLAGS[arch], "-O3", *_CONVERSION_FLAGS, *record["compile_flags"]],
        extra_ldflags=["-lcuda"],
        verbose=os.environ.get("MILES_GDN_CHUNK_TRAIN_VERBOSE_BUILD", "0") == "1",
    )


class NativeKernel:
    """One generated kernel; named bindings are mapped onto the exported argument plan.

    ``launch(grid=(x, y, z), **bindings)`` binds tensors and scalars by their
    exported names; the grid is filled in automatically.
    """

    def __init__(self, stage, arch=None, device=None):
        self.stage = stage
        self.arch = arch or device_arch(device)
        record = MODULES[stage][self.arch]
        self.record = record
        native = load(stage, self.arch)
        self._call = getattr(native, record["ffi_entry"])
        self._arg_plan = tuple(tuple(item) for item in record["arg_plan"])
        workspace_bytes = int(record["tma_workspace_bytes"])
        self.descriptor_storage = (
            torch.empty(
                workspace_bytes,
                dtype=torch.uint8,
                device=device if device is not None else "cuda",
            )
            if workspace_bytes
            else None
        )

    def launch(self, *, grid, **bindings):
        grid = tuple(int(g) for g in grid) + (1,) * (3 - len(grid))
        args = []
        used = set()
        for kind, name in self._arg_plan:
            if kind == "grid":
                args.append(grid[("grid_x", "grid_y", "grid_z").index(name)])
            elif kind == "workspace":
                args.append(self.descriptor_storage)
            else:
                if name not in bindings:
                    raise KeyError(f"{self.stage}: missing binding {name!r}")
                args.append(bindings[name])
                used.add(name)
        unexpected = set(bindings) - used
        if unexpected:
            raise KeyError(f"{self.stage}: unexpected bindings {sorted(unexpected)!r}")
        return self._call(*args)


@cache
def kernel(stage, arch):
    """Return the process-wide NativeKernel for ``stage`` on ``arch``."""
    return NativeKernel(stage, arch)
